### ISSUE TITLE
Player death event in API

### ISSUE THREAD

**Issue by bhodge4** [Exellanix/KitPvP#3]
I want a way to get the deaths of a player in another plugin. If we could make an event or make it so we can get the kills and deaths of a player in another plugin, and event in KitPvP it self, it would be great!

**Comment by Mac-Genius** [comment]
I have added player statistics to the plugins. The plugin will now track both total deaths and total kills, and will track deaths and kills per kit for each player. They can be accessed from the KitPvPAPI using Spigot's service provider.
